version: "3.6"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq-ms
    ports:
      - "5672:5672"
      - "15672:15672"
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: SQLSERVER-2022
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=1Secure*Password1"
      - "MSSQL_PID=Enterprise"
    ports:
      - "1437:1433"
    volumes:
      - /c/temp/sqlserver2022/data:/var/opt/mssql/data
      - /c/temp/sqlserver2022/log:/var/opt/mssql/log
      - /c/temp/sqlserver2022/secrets:/var/opt/mssql/secrets
  postgres:
    image: "postgres:latest"
    container_name: postgres-service-basic
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=Password12!"
      - "POSTGRES_DB=postgres"
      - "PGDATA=/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    volumes:
      - /c/temp/postgres:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaegertracing-service
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"